FROM ubuntu:18.04

# Required for steamcmd installation
RUN dpkg --add-architecture i386

# Update apt-get incl. repos
RUN apt-get -y update
RUN apt-get -y upgrade

# Install screen and Steamcmd
RUN apt-get install -y screen
RUN echo "I AGREE" | apt-get install -y steamcmd

# Update Steam
RUN /usr/games/steamcmd +quit

# COPY start.sh /usr/games/

# ENTRYPOINT [ "/usr/games/start.sh" ]